// Mocks generated by Mockito 5.3.2 from annotations
// in tp3/test/services/authentication_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tp3/models/comment.dart' as _i7;
import 'package:tp3/models/station.dart' as _i8;
import 'package:tp3/models/user.dart' as _i6;
import 'package:tp3/services/api_service.dart' as _i4;
import 'package:tp3/utils/http_detailed_response.dart' as _i3;
import 'package:tp3/utils/maybe.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMayBe_0<T> extends _i1.SmartFake implements _i2.MayBe<T> {
  _FakeMayBe_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpDetailedReponse_1 extends _i1.SmartFake
    implements _i3.HttpDetailedReponse {
  _FakeHttpDetailedReponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set client(dynamic _client) => super.noSuchMethod(
        Invocation.setter(
          #client,
          _client,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<_i2.MayBe<_i6.User>> getUserProfile(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i5.Future<_i2.MayBe<_i6.User>>.value(_FakeMayBe_0<_i6.User>(
          this,
          Invocation.method(
            #getUserProfile,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i2.MayBe<_i6.User>>);
  @override
  _i5.Future<_i2.MayBe<_i6.User>> createUserProfile(
    String? name,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUserProfile,
          [
            name,
            email,
            password,
          ],
        ),
        returnValue:
            _i5.Future<_i2.MayBe<_i6.User>>.value(_FakeMayBe_0<_i6.User>(
          this,
          Invocation.method(
            #createUserProfile,
            [
              name,
              email,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i2.MayBe<_i6.User>>);
  @override
  _i5.Future<_i2.MayBe<_i6.User>> logoutUser(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #logoutUser,
          [token],
        ),
        returnValue:
            _i5.Future<_i2.MayBe<_i6.User>>.value(_FakeMayBe_0<_i6.User>(
          this,
          Invocation.method(
            #logoutUser,
            [token],
          ),
        )),
      ) as _i5.Future<_i2.MayBe<_i6.User>>);
  @override
  _i5.Future<List<_i7.Comment>> getCommentsForSlug(String? slugName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommentsForSlug,
          [slugName],
        ),
        returnValue: _i5.Future<List<_i7.Comment>>.value(<_i7.Comment>[]),
      ) as _i5.Future<List<_i7.Comment>>);
  @override
  _i5.Future<String> getPM25Raw(String? slugName) => (super.noSuchMethod(
        Invocation.method(
          #getPM25Raw,
          [slugName],
        ),
        returnValue: _i5.Future<String>.value(''),
      ) as _i5.Future<String>);
  @override
  _i5.Future<List<_i8.Station>> fetchActiveStation() => (super.noSuchMethod(
        Invocation.method(
          #fetchActiveStation,
          [],
        ),
        returnValue: _i5.Future<List<_i8.Station>>.value(<_i8.Station>[]),
      ) as _i5.Future<List<_i8.Station>>);
  @override
  _i5.Future<_i3.HttpDetailedReponse> addComment(
    String? text,
    String? stationSlug,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addComment,
          [
            text,
            stationSlug,
            token,
          ],
        ),
        returnValue: _i5.Future<_i3.HttpDetailedReponse>.value(
            _FakeHttpDetailedReponse_1(
          this,
          Invocation.method(
            #addComment,
            [
              text,
              stationSlug,
              token,
            ],
          ),
        )),
      ) as _i5.Future<_i3.HttpDetailedReponse>);
}
